version: "3.3"

services:
  db:
    image: mysql:5.6.49
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: DB4dmin0
    networks:
      - wpsite
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:4.9.4
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Test123
    networks:
      - wpsite
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
  wordpress:
    depends_on:
      - db
    image: wordpress:5.6.0
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: dbadmin
      WORDPRESS_DB_PASSWORD: DB4dmin0
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wpsite
    # volumes:
    #   - ./132:/var/www/html
networks:
  wpsite:
volumes:
  db_data: {}
